sudo: false

addons:
  apt:
    packages:
      - libio-pty-perl # for test-terminal.perl

env:
  - TEST_OPTS=-v
  - DEFAULT_TEST_TARGET=prove

install:
  - make install prefix=$HOME/local

script:
  - make test

branches:
  only:
    - master
